services:
  postgres:
    image: postgres
    container_name: postgres-db
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: ny_taxi 
    ports:
      - "5432:5432"
  pgAdmin: 
    image: dpage/pgadmin4
    # volumes:
    #   - ./data_pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=root 
    ports:
      - "8085:80"
volumes:
  postgres-data:
